export { createOutputPath } from './createOutputPath'
export { updateStatusFailure, updateStatusSuccess, createStatus } from './status'
export { createExitCode } from './createExitCode'
export {makeGraphQlQuery} from './makeGraphQlQuery'
export { getProvider } from './getProvider'
export { isTestnet } from './isTestnet'
// export { sumPrizeAmounts } from './sumPrizeAmounts'
// export { writePrizesToOutput } from './writePrizesToOutput'
export { writeToOutput, writeStatus } from './writeOutput'
